spring.application.name=catastrophe-war
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=SPRING_SESSION
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
